// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnrvbccnlpinpxpvjybo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNucnZiY2NubHBpbnB4cHZqeWJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMDYzODksImV4cCI6MjA2NDg4MjM4OX0.oAUXoESWSn696tnKNinnfdjg9ZSIHvi6lnCc5rvbEHQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);